Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles
  Apply all migrations: admin, auth, authtoken, contenttypes, movies, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying movies.0001_initial... OK
  Applying movies.0002_alter_movie_premiere... OK
  Applying movies.0003_alter_movie_duration... OK
  Applying movies.0004_auto_20210929_1725... OK
  Applying movies.0005_alter_movie_options... OK
  Applying movies.0006_review... OK
  Applying movies.0007_alter_review_stars... OK
  Applying movies.0008_alter_review_stars... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_create_and_login_for_admin_account (test_api.TestAccountView) ... ok
test_create_and_login_for_critic_account (test_api.TestAccountView) ... ok
test_create_and_login_for_user_account (test_api.TestAccountView) ... ok
test_create_user_already_exists (test_api.TestAccountView) ... ok
test_login_non_existing_user (test_api.TestAccountView) ... ok
test_missing_login_data (test_api.TestAccountView) ... ok
test_wrong_credentials_do_not_login (test_api.TestAccountView) ... ok
test_admin_cannot_create_review (test_api.TestCriticismReviewView) ... ERROR
test_admin_cannot_update_review (test_api.TestCriticismReviewView) ... ERROR
test_cannot_create_review_with_invalid_stars (test_api.TestCriticismReviewView) ... ERROR
test_create_review_without_movie (test_api.TestCriticismReviewView) ... ok
test_critic_can_create_review (test_api.TestCriticismReviewView) ... ERROR
test_critic_can_update_review (test_api.TestCriticismReviewView) ... ERROR
test_critic_cannot_duplicate_review (test_api.TestCriticismReviewView) ... ERROR
test_update_review_from_unexisting_movie (test_api.TestCriticismReviewView) ... ok
test_update_review_that_doesnt_exist (test_api.TestCriticismReviewView) ... ERROR
test_user_cannot_create_review (test_api.TestCriticismReviewView) ... ERROR
test_user_cannot_update_review (test_api.TestCriticismReviewView) ... ERROR
test_admin_can_view_all_reviews (test_api.TestListReview) ... ERROR
test_anonymous_cannot_view_reviews (test_api.TestListReview) ... FAIL
test_critic_can_view_only_own_reviews (test_api.TestListReview) ... ERROR
test_user_cannot_view_reviews (test_api.TestListReview) ... FAIL
test_admin_can_delete_movie (test_api.TestMovieRetrieveDestroyView) ... ERROR
test_anonymous_can_filter_movies (test_api.TestMovieRetrieveDestroyView) ... ERROR
test_anonymous_cannot_delete_movies (test_api.TestMovieRetrieveDestroyView) ... ERROR
test_anonymous_cannot_filter_movies_with_the_invalid_movie_id (test_api.TestMovieRetrieveDestroyView) ... ok
test_anonymous_filter_movie_without_critic (test_api.TestMovieRetrieveDestroyView) ... ERROR
test_critic_cannot_delete_movies (test_api.TestMovieRetrieveDestroyView) ... FAIL
test_user_cannot_delete_movies (test_api.TestMovieRetrieveDestroyView) ... ok
test_user_filter_movie_with_critic (test_api.TestMovieRetrieveDestroyView) ... ERROR
test_admin_can_create_movie (test_api.TestMovieView) ... ERROR
test_anonymous_can_list_movies (test_api.TestMovieView) ... ERROR
test_anonymous_cannot_create_movie (test_api.TestMovieView) ... ok
test_critic_cannot_create_movie (test_api.TestMovieView) ... ok
test_filter_movies_with_the_filter_request (test_api.TestMovieView) ... ERROR
test_genre_cannot_repeat (test_api.TestMovieView) ... ERROR
test_output_format_data (test_api.TestMovieView) ... ERROR
test_user_cannot_create_movie (test_api.TestMovieView) ... ok

======================================================================
ERROR: test_admin_cannot_create_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 753, in test_admin_cannot_create_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_admin_cannot_update_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1128, in test_admin_cannot_update_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_cannot_create_review_with_invalid_stars (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 924, in test_cannot_create_review_with_invalid_stars
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_critic_can_create_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 805, in test_critic_can_create_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_critic_can_update_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1015, in test_critic_can_update_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_critic_cannot_duplicate_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 860, in test_critic_cannot_duplicate_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_update_review_that_doesnt_exist (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 958, in test_update_review_that_doesnt_exist
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_user_cannot_create_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 776, in test_user_cannot_create_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_user_cannot_update_review (test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1074, in test_user_cannot_update_review
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_admin_can_view_all_reviews (test_api.TestListReview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1400, in test_admin_can_view_all_reviews
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_critic_can_view_only_own_reviews (test_api.TestListReview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1308, in test_critic_can_view_only_own_reviews
    client.post("/api/movies/", self.movie_data_1, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_admin_can_delete_movie (test_api.TestMovieRetrieveDestroyView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 403, in test_admin_can_delete_movie
    movie = self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_anonymous_can_filter_movies (test_api.TestMovieRetrieveDestroyView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 319, in test_anonymous_can_filter_movies
    self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_anonymous_cannot_delete_movies (test_api.TestMovieRetrieveDestroyView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 378, in test_anonymous_cannot_delete_movies
    movie = self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_anonymous_filter_movie_without_critic (test_api.TestMovieRetrieveDestroyView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 430, in test_anonymous_filter_movie_without_critic
    self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_user_filter_movie_with_critic (test_api.TestMovieRetrieveDestroyView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 454, in test_user_filter_movie_with_critic
    self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_admin_can_create_movie (test_api.TestMovieView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 82, in test_admin_can_create_movie
    movie = self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_anonymous_can_list_movies (test_api.TestMovieView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 145, in test_anonymous_can_list_movies
    movie = self.client.post("/api/movies/", self.movie_data, format="json")
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_filter_movies_with_the_filter_request (test_api.TestMovieView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 189, in test_filter_movies_with_the_filter_request
    movie_1 = self.client.post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_genre_cannot_repeat (test_api.TestMovieView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 166, in test_genre_cannot_repeat
    movie_1 = self.client.post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
ERROR: test_output_format_data (test_api.TestMovieView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 226, in test_output_format_data
    movie_1 = self.client.post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/tk/kenzie/q4/training/kmdb-retake/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/tk/kenzie/q4/training/kmdb-retake/movies/serializers.py", line 34, in create
    movie.genres.add(gen) # Adicionando o genre ao movie, como se fosse um append
AttributeError: 'tuple' object has no attribute 'genres'

======================================================================
FAIL: test_anonymous_cannot_view_reviews (test_api.TestListReview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1263, in test_anonymous_cannot_view_reviews
    self.assertEqual(response.status_code, 401)
AssertionError: 404 != 401

======================================================================
FAIL: test_user_cannot_view_reviews (test_api.TestListReview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 1283, in test_user_cannot_view_reviews
    self.assertEqual(response.status_code, 403)
AssertionError: 404 != 403

======================================================================
FAIL: test_critic_cannot_delete_movies (test_api.TestMovieRetrieveDestroyView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tk/kenzie/q4/training/kmdb-retake/test_api.py", line 349, in test_critic_cannot_delete_movies
    self.assertEqual(status_code, 403)
AssertionError: 404 != 403

----------------------------------------------------------------------
Ran 38 tests in 5.607s

FAILED (failures=3, errors=21)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
